# Generated by Django 5.1.1 on 2024-10-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0002_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='produto',
            new_name='produtos',
        ),
        migrations.AddField(
            model_name='produto',
            name='autores',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='elenco',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
